server:
  port: ${APP_PORTAL_PORT}
  servlet:
    context-path: /api/portal
spring:
  application:
    name: portal
  data:
    redis.repositories.enabled: false
  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}?reWriteBatchedInserts=true
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 12
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
        jdbc.batch_size: 1000
        dialect: org.bmsource.dwh.common.db.CustomPostgreSQLDialect
    database-platform: org.bmsource.dwh.common.db.CustomPostgreSQLDialect
  flyway:
    baseline-version: 1
  servlet:
    multipart:
      enabled: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  batch:
    job:
      enabled: false
