stages:
  - build
  - coverage

java-build:
  stage: build
  variables:
    SHA: $(git rev-parse HEAD)
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  image: maven:3.6.3-jdk-8
  services:
    - postgres
    - redis
  script:
    - cat /etc/*-release
    - apt-get update
    - apt-get install -y postgresql-client
    - PGPASSWORD=postgres psql -h "postgres" -U "postgres" -d "postgres" -a -f ./.db/init.sql
    - export $(cat .env.ci.gitlab | xargs)
    - mvn -ntp clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    #- env $(cat .env.ci.gitlab) java -Dspring.profiles.active=integration-test -jar ./app-migrator/target/application.jar
    - env $(cat .env.ci.gitlab) mvn package -DskipTests -pl app-migrator && mvn exec:java -pl app-migrator -Dspring.profiles.active=cli,integration-test
    - mvn -ntp clean install
  artifacts:
    paths:
      - app-importer/target/
      - app-migrator/target/
      - app-olap/target/
      - app-portal/target/
      - app-security/target/
      - lib-common/target/

react-build:
  stage: build
  variables:
    SHA: $(git rev-parse HEAD)
  image: node
  cache:
    paths:
      - react-app/node_modules/
  script:
    - cd react-app
    - yarn install
    - yarn test:coverage
  artifacts:
    paths:
      - react-app/build/
      - react-app/coverage/

codecov:
  stage: coverage
  script:
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f app-importer/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f app-migrator/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f app-olap/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f app-portal/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f app-security/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f lib-common/target/site/jacoco/jacoco.xml -c -F java
    - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN -f react-app/coverage/coverage-final.json -c -F reactapp
#    - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN -f lib-common/target/site/jacoco/jacoco.xml -c -F java
#    - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN -f app-importer/target/site/jacoco/jacoco.xml -c -F java
#    - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN -f app-olap/target/site/jacoco/jacoco.xml -c -F java
#    - curl -s https://codecov.io/bash | bash -s - -t $CODECOV_TOKEN -f react-app/coverage/coverage-final.json -c -F reactapp
