coverage:
  status:
    project:
      default: off
      java:
        flags: java
        target: 70%
      reactapp:
        flags: reactapp
        target: 70%
flags:
  java:
    paths:
      - app-importer/src
      - app-migrator/src
      - app-olap/src
      - app-portal/src
      - app-security/src
      - lib-common/src
  reactapp:
    paths:
      - react-app/src
