coverage:
  status:
    project:
      default: off
      java:
        flags: java
        target: 50%
      react:
        flags: react
        target: 50%
flags:
  java:
    paths:
      - app-importer/src
      - app-migrator/src
      - app-olap/src
      - app-portal/src
      - app-security/src
      - lib-common/src
  react:
    paths:
      - react-app/src
