coverage:
  status:
    project:
      default: off
      java:
        flags: java
        target: 30%
#      react:
#        flags: react
#        target: 30%
flags:
  java:
    paths:
      - app-importer/src/main/java
      - app-migrator/src/main/java
      - app-olap/src/main/java
      - app-portal/src/main/java
      - app-security/src/main/java
      - lib-common/src/main/java
#  react:
#    paths:
#      - web-dwh/src

ignore:
  - "**/src/main/test/**/*"
  - "**/target/**/*"
  - "**/build/**/*"
  - "**/*.spec.js"
