version: '3.7'
services:
  db:
    image: postgres:10.3
    container_name: db
    volumes:
      - ./.db/seeds:/.db/seeds
      - ./.db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "log_statement=all"
  db-test:
    image: postgres:10.3
    container_name: db-test
    volumes:
      - ./.db/seeds:/.db/seeds
      - ./.db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${PG_TEST_PORT}:5432
    environment:
      POSTGRES_DB: $PG_TEST_DATABASE
      POSTGRES_USER: $PG_TEST_USER
      POSTGRES_PASSWORD: $PG_TEST_PASSWORD
    command:
      - "postgres"
      - "-c"
      - "max_connections=100"
      - "-c"
      - "shared_buffers=256MB"
      - "-c"
      - "log_statement=all"
  redis:
    image: redis:4.0.5-alpine
    container_name: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 8081:80
    volumes:
      - ./.dev/nginx.local.conf:/etc/nginx/nginx.conf

#  web-dwh:
#    build:
#      dockerfile: Dockerfile
#      context: ./web-dwh
#    ports:
#      - 3000:3000
