#!/usr/bin/env bash

set -euo pipefail
shopt -s expand_aliases

if ! [[ -x "$(command -v docker-compose)" ]]; then
  echo "Please install Docker and then fire the script again"
  quit
fi

DOCKER="docker"
COMPOSE="docker-compose"
YARN_BIN="/usr/bin/yarn"


DWH_ENV=.env.local

export $(cat $DWH_ENV | xargs)
#printenv

function quit() {
  echo >&2 "$@"
  exit 1
}

function info() {
  echo -e "\x1B[33m$1\x1B[0m"
}

function success() {
  echo -e "\x1B[32m$1\x1B[0m"
}

function appStart() {
  info "== Starting App ... =="
  info "== Starting infrastructure services =="
  #mvn -ntp clean install -DskipTests
  DWH_ENV=.env
  env $(cat $DWH_ENV) $COMPOSE -f docker-compose.yml  -f docker-compose.local.yml up -d --remove-orphans --build
}

function appStop() {
  info "== Shutting down currently running Stack ... =="
  DWH_ENV=.env
  env $(cat $DWH_ENV) $COMPOSE -f docker-compose.local.yml -f docker-compose.yml stop
}

function stackStart() {
  appStop
  info "== Starting Stack ... =="
  info "== Starting infrastructure services =="
  DWH_ENV=.env.local
  env $(cat $DWH_ENV) $COMPOSE -f docker-compose.yml up -d --remove-orphans --build

  info "== Checking running services =="
  ${COMPOSE} ps

  success "== Done =="
}

function dbRestore() {
  [[ ! -z $1 ]] || quit "Please specify database name"
  [[ ! -z $2 ]] || quit "Please specify dump path"
  ${COMPOSE} exec db sh -c "psql -U postgres -v ON_ERROR_STOP=1 --single-transaction -q -f /$2  $1 >/dev/null"
}

function init() {
  success "== Done =="
}

function migrations() {
  mvn package -DskipTests -pl migrator && mvn exec:java -pl migrator
  success "== Done =="
}

function migrationsTest() {
  mvn package -DskipTests -pl migrator && mvn exec:java -pl migrator -Dspring.profiles.active=integration-test
  success "== Done =="
}

function kubeStart() {
  export SHA=$(git rev-parse HEAD)

#  mvn clean install -DskipTests
#
#  docker build -t marecica2/dwh-react-app -t marecica2/dwh-react-app:$SHA -f ./react-app/Dockerfile ./react-app
#  docker build -t marecica2/dwh-migrator -t marecica2/dwh-migrator:$SHA -f ./migrator/Dockerfile ./migrator
#  docker build -t marecica2/dwh-importer -t marecica2/dwh-importer:$SHA -f ./importer/Dockerfile ./importer

  kubectl apply -f .k8s

  kubectl set image deployments/dwh-react-app-deployment server=marecica2/dwh-react-app
  kubectl set image deployments/migrator-deployment server=marecica2/dwh-migrator
  kubectl set image deployments/importer-deployment server=marecica2/dwh-importer

  success "== Done =="
}


if [[ $# -gt 0 ]]; then

  if [[ "$1" == "start" ]]; then
    stackStart
    appStart $@

  elif [[ "$1" == "stack-start" ]]; then
    stackStart

  elif [[ "$1" == "stack-stop" ]]; then
    appStop

  elif [[ "$1" == "k8s-start" ]]; then
    kubeStart

  elif [[ "$1" == "stack-clear" ]]; then
    echo "Cleaning docker containers..."
    appStop
    ${DOCKER} system prune
    ${DOCKER} images -q --no-trunc | xargs ${DOCKER} rmi -f || true

  elif [[ "$1" == "init" ]]; then
    init

  elif [[ "$1" == "migrations" ]]; then
    migrations

  elif [[ "$1" == "migrations-test" ]]; then
    migrationsTest

  elif [[ "$1" == "reset" ]]; then
    appStop
    ${COMPOSE} rm -f
    ${COMPOSE} pull
    stackStart
    migrations
    migrationsTest
    sleep 10
    init
    appStart $@

  elif [[ "$1" == "app-start" ]]; then
    appStart $@

  elif [[ "$1" == "yarn" ]]; then
    shift 1
    $YARN_BIN $@

  elif [[ "$1" == "module-yarn" ]]; then
    shift 1
    [[ ! -z $1 ]] || quit "Please specify module name"
    (cd modules/$1 && shift 1 && ../../$YARN_BIN $@)

  elif [[ -d "modules/${1}" ]]; then
    (cd modules/$1 && shift 1 && $@)

  elif [[ "$1" == "app-test" ]]; then
    $YARN_BIN install
    $YARN_BIN test

  elif [[ "$1" == "aws" ]]; then
    shift 1
    MODULE="$1"
    shift 1
    ARGS="$@"
    if [[ "$MODULE" == "sqs" ]]; then
      ${COMPOSE} exec \
        localstack bash -c "aws sqs --endpoint-url=http://localstack:4570 --region=eu-central-1 $ARGS"
    else
      ${COMPOSE} exec \
        localstack bash -c "aws $MODULE --endpoint-url=http://localstack:4572 $ARGS"
    fi

  elif [[ "$1" == "redis" ]]; then
    shift 1
    ${COMPOSE} exec redis redis-cli

  elif [[ "$1" == "psql" ]]; then
    shift 1
    ${COMPOSE} exec \
      ${1:-db} bash -c "psql -U postgres"

  elif [[ "$1" == "db-dump" ]]; then
    shift 1
    [[ ! -z $1 ]] || quit "Please specify database name"
    TIMESTAMP=$(date +%Y%m%d_%H%M)
    ${COMPOSE} exec db sh -c "pg_dump -U postgres --clean --if-exists --no-owner $1 > /.db/seeds/postgres_$1_$TIMESTAMP.sql"
    printf "\x1B[33mDump saved at: .db/seeds/postgres_$1_$TIMESTAMP.sql\x1B[0m\n"

  elif [[ "$1" == "db-dump-tests" ]]; then
    shift 1
    [[ ! -z $1 ]] || quit "Please specify database name"
    ${COMPOSE} exec db sh -c "pg_dump -U postgres --clean --if-exists --no-owner --schema-only -n access -n common -n data_dump1 $1 > /.db/seeds/dump.sql"
    printf "\x1B[33mDump saved at: .db/seeds/dump.sql\x1B[0m\n"

  elif [[ "$1" == "db-restore" ]]; then
    shift 1
    dbRestore $@

  else
    ${COMPOSE} "$@"
  fi

else
  ${COMPOSE} ps
fi
