#!/usr/bin/env bash

# Detect if sudo needed
USER="$(whoami)"
SUDO=""
# It looks like sudo isn't require on Mac
#if [ ! "${USER}" == "root" ];then
#  SUDO=$(id -Gn $USER | grep -q docker) || SUDO="sudo "
#fi

DOCKER="${SUDO}docker"
COMPOSE="${SUDO}docker-compose"

function die () {
    echo >&2 "$@"
    exit 1
}

if [ $# -gt 0 ];then

  if [ "$1" == "exec" ]; then
    shift 1
    ARGS="$@"
    ${COMPOSE} exec \
      app bash -c "$ARGS"

  elif [ "$1" == "clean" ]; then
    shift 1
    ${DOCKER} volume ls -qf dangling=true | xargs -r ${DOCKER} volume rm
    ${DOCKER} images -q --no-trunc | xargs -r ${DOCKER} rmi || true

  elif [ "$1" == "yarn" ]; then
    shift 1
    ${COMPOSE} run --rm -w /app \
        app \
        yarn "$@"

  elif [ "$1" == "db-dump" ]; then
    shift 1
    [ ! -z $1 ] || die "Please specify database name"
    ${COMPOSE} exec db sh -c "pg_dump -U postgres --clean --if-exists --no-owner -n public $1 | gzip > /.db/seeds/postgres_$1_$(date +%Y%m%d_%H%M).sql.gz"

  elif [ "$1" == "db-restore" ]; then
    shift 1
    [ ! -z $1 ] || die "Please specify database name"
    [ ! -z $2 ] || die "Please specify dump path"
    ${COMPOSE} exec db sh -c "gunzip -c /$2 | psql -U postgres --single-transaction -a $1"

  else
      ${COMPOSE} "$@"
  fi
else
  ${COMPOSE} ps
fi
