set search_path to "tenant0000000000000001";
truncate table batch_job_execution_params restart identity cascade;
truncate table batch_step_execution_context restart identity cascade;
truncate table batch_step_execution restart identity cascade;
truncate table batch_job_execution_context restart identity cascade;
truncate table batch_job_execution restart identity cascade;
truncate table batch_job_instance restart identity cascade;
truncate table zip_code_location restart identity cascade;
truncate table service_type_taxonomy restart identity cascade;
truncate table service_type_mapping restart identity cascade;
truncate table standard_rate_card restart identity cascade;
truncate table mapping_preset restart identity cascade;
truncate table fact_raw restart identity cascade;
truncate table fact restart identity cascade;
